routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\Admin\MainController::class, 'main'])->name('main');

Route::prefix('coins/')->name('coins.')->group(function (){
    Route::get('available', \App\Http\Livewire\Admin\Coins\AvailableCoins::class)->name('available');
    Route::get('all', \App\Http\Livewire\Admin\Coins\All::class)->name('all');
    Route::get('gaps', \App\Http\Livewire\Admin\Coins\Gaps::class)->name('gaps');
});

Route::get('/orders', \App\Http\Livewire\Admin\ExchangeApplicationsList::class)->name('orders.list');
Route::get('/orders/{id}', \App\Http\Livewire\Admin\ExchangeApplicationView::class)->name('orders.view');

Route::name('settings.')->prefix('settings/')->group(function (){
    Route::get('/localization', \App\Http\Livewire\Admin\LocalizationList::class)->name('localization');
    Route::get('/main', \App\Http\Livewire\Admin\Settings::class)->name('main');
});


Route::name('pages.')->prefix('pages/')->group(function (){
    Route::get('/{key}', [\App\Http\Controllers\Admin\Pages\EditPageController::class, 'edit'])->name('edit');
    Route::post('/{key}', [\App\Http\Controllers\Admin\Pages\EditPageController::class, 'store'])->name('store');
});

Route::get('faq/list', [\App\Http\Controllers\Admin\FaqController::class, 'list'])->name('faq.list');
Route::get('faq/create', [\App\Http\Controllers\Admin\FaqController::class, 'create'])->name('faq.create');
Route::post('faq/question/store', [\App\Http\Controllers\Admin\FaqController::class, 'store'])->name('faq.store');
Route::get('faq/question/{question}/edit', [\App\Http\Controllers\Admin\FaqController::class, 'edit'])->name('faq.question.edit');
Route::put('faq/question/{question}/update', [\App\Http\Controllers\Admin\FaqController::class, 'update'])->name('faq.question.update');
Route::delete('faq/question/{question}', [\App\Http\Controllers\Admin\FaqController::class, 'delete'])->name('faq.question.delete');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', [\App\Http\Controllers\MainController::class, 'test']);

Route::localizedGroup(function () {

        Route::get('/', \App\Http\Livewire\Exchange::class)->name('main');
        Route::get('/order/{uuid}', \App\Http\Livewire\ViewApplication::class)
            ->name('order.view');

        Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

        Route::get('/support', [\App\Http\Controllers\PageController::class, 'support'])->name('support');
        Route::get('/reserve', [\App\Http\Controllers\PageController::class, 'reserve'])->name('reserve');
        Route::get('/crypto-check', [\App\Http\Controllers\PageController::class, 'cryptoCheck'])
            ->middleware('auth')
            ->name('crypto-check');
        Route::get('/partner', [\App\Http\Controllers\PageController::class, 'partner'])->name('partner');
        Route::get('/faq', [\App\Http\Controllers\PageController::class, 'faq'])->name('faq');
        Route::get('/history', [\App\Http\Controllers\PageController::class, 'history'])->middleware('auth')->name('history');
        Route::get('/privacy', [\App\Http\Controllers\PageController::class, 'privacy'])->name('privacy');
        Route::get('/terms', [\App\Http\Controllers\PageController::class, 'terms'])->name('terms');

        Auth::routes();
});

app/Models/ExchangeApplication.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ExchangeApplication extends Model
{
    use HasFactory;

    public const STATUS_NEW = 'new';
    public const STATUS_CANCELLED = 'cancelled';
    public const STATUS_INSPECTION = 'inspection';
    public const STATUS_PAYED = 'payed';
    public const STATUS_CONFIRMATION = 'confirmation';
    public const STATUS_COMPLETED = 'completed';

    protected $guarded = [];

    protected $casts = [
        'created_at' => 'datetime'
    ];

    public function getIsActualAttribute() :bool
    {
        return now() < $this->created_at->addMinutes(config('app.exchange_time'));
    }


    public function fromCoin()
    {
        return $this->belongsTo(AvailableCoin::class, 'from_coin_id');
    }

    public function toCoin()
    {
        return $this->belongsTo(AvailableCoin::class, 'to_coin_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getStatusNameAttribute()
    {
        return __('order_status.'.$this->status);
    }
}

app/Http/Livewire/Admin/Coins/All.php
<?php

namespace App\Http\Livewire\Admin\Coins;

use App\Models\Coin;
use Livewire\Component;
use Livewire\WithPagination;

class All extends Component
{
    use WithPagination;

    protected $paginationTheme = 'bootstrap';

    public $search;

    public function getCoins()
    {
        $query = Coin::query();
        if($this->search) {
            $query->where('name', 'LIKE', "%$this->search%");
        }

        return $query->paginate(50);
    }

    public function render()
    {
        $coins = $this->getCoins();
        return view('livewire.admin.coins.all', compact('coins'))
            ->extends('admin.layouts.main')
            ->section('content');
    }
}

app/Http/Livewire/Admin/Coins/AvailableCoins.php
<?php

namespace App\Http\Livewire\Admin\Coins;

use App\Http\Livewire\Traits\HasSwal;
use App\Models\AvailableCoin;
use App\Models\Coin;
use App\Models\ExchangeApplication;
use App\Models\Gap;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Storage;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;

class AvailableCoins extends Component
{
    use WithPagination, HasSwal, WithFileUploads;

    protected $paginationTheme = 'bootstrap';

    protected $listeners = [
        'removeAvailableCoin'
    ];

    public $showCreateModal = false;

    public $newCoin = [];

    public $search;

    public $showEditModal = false;

    public $editCoin = [];

    public function mount()
    {
        $this->newCoin['type'] = 'coin';
    }

    public function getAvailableCoins()
    {
        $query = AvailableCoin::query();

        if($this->search) {
            $query = $query->where('name', 'LIKE', "%$this->search%");
        }

        return $query->paginate(50);
    }

    public function closeCreateModal()
    {
        $this->showCreateModal = false;
    }

    public function showCreateModal()
    {
        $this->showCreateModal = true;
    }

    public function removeConfirmation($id)
    {
        $this->showSwalConfirm('error', 'Вы уверены что хотите удалить монету?', 'removeAvailableCoin', $id);
    }

    public function removeAvailableCoin(AvailableCoin $availableCoin)
    {
        Gap::where('coin_from_id', $availableCoin->id)->orWhere('coin_to_id', $availableCoin->id)->delete();
        ExchangeApplication::where('from_coin_id', $availableCoin->id)->orWhere('to_coin_id', $availableCoin->id)->delete();
        $availableCoin->translations()->delete();
        $availableCoin->delete();
    }

    protected function getRules()
    {
        return [
            'newCoin.coin_id' => ['nullable', 'exists:coins,id'],
            'newCoin.icon' => ['required', 'image'],
            'newCoin.name' => ['required', 'string', 'min:3', 'max:190'],
            'newCoin.type' => ['required', 'in:card,coin'],
            'newCoin.ru.description' => ['required', 'string', 'min:3', 'max:190'],
            'newCoin.en.description' => ['required', 'string', 'min:3', 'max:190'],
            'newCoin.pl.description' => ['required', 'string', 'min:3', 'max:190'],
            'newCoin.wallet' => ['required', 'string', 'min:3', 'max:190'],

        ];
    }

    public function createCoin()
    {
        $data = $this->validate() ? $this->validate()['newCoin'] : null;
        $iconPath = $data['icon']->store('public/icons');
        $iconPath = str_replace('public/icons', 'storage/icons', $iconPath);
        $data['icon'] = $iconPath;

        if( AvailableCoin::create($data) ) {

            $this->resetNewCoin();
            $this->closeCreateModal();
            Artisan::call('prices:update');
            $this->showSwalToast('success', 'Валюта успешно добавлена');
        } else {
            $this->showSwalToast('danger', 'Ошибка добавления');
        }


    }

    protected function resetNewCoin()
    {
        $this->newCoin = [];
        $this->newCoin['type'] = 'coin';
    }

    public function editCoin($id)
    {
        $coin = AvailableCoin::findOrFail($id);
        $this->editCoin['id'] = $coin->id;
        $this->editCoin['name'] = $coin->name;
        $this->editCoin['wallet'] = $coin->wallet;
        $this->editCoin['min'] = $coin->min;
        $this->editCoin['max'] = $coin->max;
        $this->editCoin['ru']['description'] = $coin->translate('ru')->description ?? '';
        $this->editCoin['pl']['description'] = $coin->translate('pl')->description ?? '';
        $this->editCoin['en']['description'] = $coin->translate('en')->description ?? '';
        $this->openEditModal();

    }

    public function openEditModal()
    {
        $this->showEditModal = true;
    }

    public function closeEditModal()
    {
        $this->editCoin = [];
        $this->showEditModal = false;
    }

    protected function getEditCoinRules()
    {
        return [
            'editCoin.id' => ['required', 'exists:available_coins,id'],
            'editCoin.name' => ['required', 'string', 'min:3', 'max:190'],
            'editCoin.wallet' => ['required', 'string', 'min:3', 'max:190'],
            'editCoin.min' => ['required', 'between:0.0001,1000'],
            'editCoin.max' => ['required', 'between:0.0001,1000'],
            'editCoin.ru.description' => ['required', 'string', 'min:3', 'max:190'],
            'editCoin.en.description' => ['required', 'string', 'min:3', 'max:190'],
            'editCoin.pl.description' => ['required', 'string', 'min:3', 'max:190'],
        ];
    }

    public function saveEditCoin()
    {
        $data = $this->validate($this->getEditCoinRules());
        $data = $data['editCoin'];
        $coin = AvailableCoin::findOrFail($this->editCoin['id']);
        $coin->update($data);
        $this->closeEditModal();
        $this->showSwalToast('success', 'Сохранено');
    }

    public function render()
    {
        $coins = $this->getAvailableCoins();

        return view('livewire.admin.coins.available-coins', compact('coins'))
            ->extends('admin.layouts.main')
            ->section('content');
    }
}

app/Http/Livewire/Admin/Coins/Gaps.php
<?php

namespace App\Http\Livewire\Admin\Coins;

use App\Http\Livewire\Traits\HasSwal;
use App\Models\AvailableCoin;
use App\Models\Gap;
use Livewire\Component;
use Livewire\WithPagination;

class Gaps extends Component
{
    use WithPagination, HasSwal;

    protected $listeners = ['deleteGap'];

    public $availableCoins;

    public $newGap = [];
    public $editGap;

    public $showCreateModal = false;
    public $showEditModal = false;

    protected $paginationTheme = 'bootstrap';

    public function mount()
    {
        $this->availableCoins = $this->getAvailableCoins();
        $this->newGap['coin_from_id'] = $this->availableCoins->first()->id ?? null;
        $this->newGap['coin_to_id'] = $this->availableCoins->last()->id;
    }

    public function showEditModal(Gap $gap)
    {
        $this->editGap['id'] = $gap->id;
        $this->editGap['percent'] = $gap->percent;
        $this->showEditModal = true;
    }

    public function closeEditModal()
    {
        $this->showEditModal = false;
        $this->editGap = null;

    }

    protected function resetEditGap()
    {
        $this->editGap = null;
        $this->closeEditModal();
    }

    public function saveEditGap()
    {
        if($this->editGap['id']) {
            Gap::findOrFail($this->editGap['id'])->update(['percent' => $this->editGap['percent']]);
            $this->resetEditGap();
            $this->showSwalToast('success', 'Успешно отредактировано');
        }
    }

    public function deleteConfirmation($id)
    {
        $this->showSwalConfirm('error', 'Вы уверены?', 'deleteGap', $id);
    }

    public function deleteGap(Gap $gap)
    {
        $gap->delete();
        $this->showSwalToast('success', 'Удалено');
    }

    public function showCreateModal()
    {
        $this->showCreateModal = true;
    }

    public function closeCreateModal()
    {
        $this->showCreateModal = false;
    }

    protected function getNewGapRules()
    {
        return [
            'newGap.coin_from_id' => ['required', 'exists:available_coins,id'],
            'newGap.coin_to_id' => ['required', 'exists:available_coins,id'],
            'newGap.percent' => ['required', 'between:1,50'],
        ];
    }

    protected function resetNewGap()
    {
        $this->newGap['coin_from_id'] = $this->availableCoins->first()->id ?? null;
        $this->newGap['coin_to_id'] = $this->availableCoins->last()->id;
        $this->newGap['percent'] = null;
    }

    public function saveNewGap()
    {
        $this->validate($this->getNewGapRules());

        Gap::updateOrCreate(
            ['coin_from_id' => $this->newGap['coin_from_id'], 'coin_to_id' => $this->newGap['coin_to_id']],
            ['percent' => $this->newGap['percent']]
        );

        $this->resetNewGap();
        $this->closeCreateModal();
        $this->showSwalToast('success', 'Обновлено');


    }

    protected function getGaps()
    {
        return Gap::paginate(50);
    }

    protected function getAvailableCoins()
    {
        return AvailableCoin::with('originalCoin')->get();
    }

    public function render()
    {
        $gaps = $this->getGaps();

        return view('livewire.admin.coins.gaps', compact('gaps'))
            ->extends('admin.layouts.main')
            ->section('content');
    }
}

app/Http/Livewire/Admin/ExchangeApplicationView.php
<?php

namespace App\Http\Livewire\Admin;

use App\Http\Livewire\Traits\HasSwal;
use App\Models\ExchangeApplication;
use Livewire\Component;

class ExchangeApplicationView extends Component
{
    use HasSwal;
    public $exchangeApplication;

    protected $listeners = [
        'setStatus', 'deleteOrder'
    ];

    public function deleteConfirmation($id)
    {
        $this->showSwalConfirm('error', 'Вы уверены?', 'deleteOrder', $id);
    }

    public function deleteOrder(ExchangeApplication $order)
    {
        $order->delete();
        return redirect()->route('admin.orders.list');
    }

    public function mount($id)
    {
        $this->exchangeApplication = ExchangeApplication::findOrFail($id);
    }

    public function setStatusConfirmation($status)
    {
        $this->showSwalConfirm('error', 'Вы уверены?', 'setStatus', $status);
    }

    public function setStatus($status)
    {
        $this->exchangeApplication->update(['status' => $status]);
        $this->exchangeApplication->refresh();
    }

    public function render()
    {
        return view('livewire.admin.exchange-application-view')
            ->extends('admin.layouts.main')
            ->section('content');
    }
}

app/Http/Livewire/Admin/ExchangeApplicationsList.php
<?php

namespace App\Http\Livewire\Admin;

use App\Http\Livewire\Traits\HasSwal;
use App\Models\ExchangeApplication;
use Livewire\Component;
use Livewire\WithPagination;
use function Sodium\compare;

class ExchangeApplicationsList extends Component
{
    use WithPagination, HasSwal;

    protected $paginationTheme = 'bootstrap';

    protected function getApplications()
    {
        return ExchangeApplication::orderBy('created_at', 'DESC')->paginate(20);
    }

    public function viewOrder($id)
    {
        return redirect()->route('admin.orders.view', ['id' => $id]);
    }

    public function render()
    {
        $applications = $this->getApplications();

        return view('livewire.admin.exchange-applications-list', compact('applications'))
            ->extends('admin.layouts.main')
            ->section('content');
    }
}

app/Http/Livewire/LastTransactions.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class LastTransactions extends Component
{
    public function render()
    {
        return view('livewire.last-transactions');
    }
}

app/Http/Livewire/Traits/HasSwal.php
<?php

namespace App\Http\Livewire\Traits;

trait HasSwal
{
    public function showSwalToast($type, $message, $title = null)
    {
        $this->dispatchBrowserEvent('swal:toast', [
            'type' => $type,
            'text' => $message,
            'title' => $title
        ]);
    }

    public function showSwalModal($type, $message, $title = null)
    {
        $this->dispatchBrowserEvent('swal:modal', [
            'type' => $type,
            'text' => $message,
            'title' => $title
        ]);
    }

    public function showSwalConfirm($type, $message, $emit = null, $id = null, $title = null)
    {
        $this->dispatchBrowserEvent('swal:confirm', [
            'type' => $type,
            'title' => $title,
            'text' => $message,
            'emit' => $emit,
            'id' => $id
        ]);
    }
}

resources/views/livewire/admin/exchange-application-view.blade.php
<div>
    <div class="container">
        <div class="row">
            <div class="col-10 offset-1">
                <div class="card">
                    <div class="card-header">
                        Заявка на обмен № <b>{{ $exchangeApplication->id }}</b>
                    </div>
                    <div class="card-body">
                        <div class="alert alert-danger text-center">
                            Деньги должны зачислиться на кошелек {{ $exchangeApplication->fromCoin->name }}:  {{ $exchangeApplication->fromCoin->wallet }}
                        </div>
                        <ul class="list-group list-group-flush text-center">
{{--                            <li class="list-group-item">UUID: {{ $exchangeApplication->uuid }}</li>--}}
                            @if($exchangeApplication->user_id)
                                <li class="list-group-item">Ползователь: {{ $exchangeApplication->user_id }}</li>
                            @endif
                            <li class="list-group-item">
                                <h4>Обмен </h4>
                                <h3>{{ $exchangeApplication->amount_from }} {{ $exchangeApplication->fromCoin->name }}</h3>
                                <h4>></h4>
                                <h3>{{ $exchangeApplication->amount_to }} {{ $exchangeApplication->toCoin->name }}</h3>
                            </li>
                            <li class="list-group-item">
                                Кошелек {{ $exchangeApplication->toCoin->name }} пользователя: <h4>{{ $exchangeApplication->wallet_to }}</h4>
                            </li>
                            <li class="list-group-item">
                                Дата заявки: <h4>{{ $exchangeApplication->created_at->format('d.m.Y H:i') }}</h4>
                            </li>
                            <li class="list-group-item">
                                Статус: <h4>{{ $exchangeApplication->status_name }}</h4>
                            </li>
                            <div class="alert alert-success text-center">
                                Переведите {{ $exchangeApplication->amount_to }} {{ $exchangeApplication->toCoin->name }} на адрес {{ $exchangeApplication->wallet_to }}
                            </div>
                            <li class="list-group-item">
                                <button wire:click="setStatusConfirmation('{{ \App\Models\ExchangeApplication::STATUS_NEW }}')" class="btn btn-success" @if($exchangeApplication->status === 'new') disabled @endif>Новая</button>
                                >
                                <button  class="btn btn-primary" disabled >На проверке</button>
                                >
                                <button wire:click="setStatusConfirmation('{{ \App\Models\ExchangeApplication::STATUS_PAYED }}')" class="btn btn-success" @if($exchangeApplication->status === 'payed') disabled @endif>Оплачена</button>
                                >
                                {{--                    <button class="btn btn-warning" @if($exchangeApplication->status === 'confirmation') disabled @endif>Ожидает подтвреждения</button>--}}
                                {{--                    >--}}
                                <button wire:click="setStatusConfirmation('{{ \App\Models\ExchangeApplication::STATUS_COMPLETED }}')" class="btn btn-dark" @if($exchangeApplication->status === 'completed') disabled @endif>Завершена</button>
                            </li>
                            <li class="list-group-item">
                                <button wire:click="setStatusConfirmation('{{ \App\Models\ExchangeApplication::STATUS_CANCELLED }}')" class="btn btn-danger" @if($exchangeApplication->status === 'cancelled') disabled @endif>Отменить заявку</button>
                            </li>
                            <li class="list-group-item">
                                <button wire:click="deleteConfirmation({{ $exchangeApplication->id }})" class="btn btn-danger">Удалить заявку</button>
                            </li>
                        </ul>
                    </div>


                </div>
            </div>
        </div>

    </div>
</div>

resources/views/livewire/admin/exchange-applications-list.blade.php
<div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    <h4>Заявки на обмен</h4>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">UUID</th>
                        <th scope="col">Отдает</th>
                        <th scope="col">Сума обмена</th>
                        <th scope="col">Получает</th>
                        <th scope="col">Сума получения</th>
                        <th scope="col">Кошелек получения</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Дата обмена</th>

                    </tr>
                    </thead>
                    <tbody>
                    @forelse($applications as $order)
                        <tr wire:click="viewOrder({{ $order->id }})" style="cursor: pointer">
                            <th scope="row">{{ $order->id }}</th>
                            <td>{{ $order->uuid }}</td>
                            <td>
                                {{ $order->fromCoin->name }}
                                <br>
                                <img src="/{{ $order->fromCoin->icon }}" width="30">
                            </td>
                            <td>{{ $order->amount_from }}</td>
                            <td>
                                {{ $order->toCoin->name }}
                                <br>
                                <img src="/{{ $order->toCoin->icon }}" width="30">
                            </td>
                            <td>{{ $order->amount_to }}</td>
                            <td>{{ $order->wallet_to }}</td>
                            <td>{{ $order->status_name }}</td>
                            <td>{{ $order->created_at->format('d.m.Y H:i') }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="9">Пусто</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            {{ $applications->links() }}
        </div>
    </div>
</div>

resources/views/livewire/admin/localization-list.blade.php
<div>
{{--    @livewire('admin.localization.edit-modal')--}}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-12 d-flex justify-content-end align-items-end p-3">
                    <div class=" bg-transparent">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="ibox ">
        <div class="ibox-title p-3">
            <div class="row">
                <div class="col-6 text-left">
                    <h3>Переводы</h3>
                </div>
                <div class="col-6 text-right">
                    <input type="text" class="form-control" placeholder="Поиск" wire:model="search">
                    {{--                    <a href="{{ route('admin.pages.main.block.create') }}"><button class="btn btn-primary">Створити</button></a>--}}
                </div>
            </div>


        </div>
        {{--        @if ($blocks->count())--}}
        <div class="ibox-content">
            <div class="row">
                <div class="col-2">
                    <input type="text" class="form-control" placeholder="Група" wire:model="newLine.group">
                </div>
                <div class="col-2">
                    <input type="text" class="form-control" placeholder="Ключ" wire:model="newLine.key">
                </div>
                <div class="col-2">
                    <input type="text" class="form-control" placeholder="Текст RU" wire:model="newLine.text.ru">
                </div>
                <div class="col-2">
                    <input type="text" class="form-control" placeholder="Текст EN" wire:model="newLine.text.en">
                </div>
                <div class="col-2">
                    <input type="text" class="form-control" placeholder="Текст PL" wire:model="newLine.text.pl">
                </div>
                <div class="col-2 text-right">
                    <button wire:click="saveLine" class="btn btn-primary">Создать</button>
                </div>
            </div>
            <div class="row">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Група</th>
                            <th>Ключ</th>
                            <th>Тект RU</th>
                            <th>Тект EN</th>
                            <th>Тект PL</th>
                            <th>Код</th>
                            <th>Дія</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($lines as $line)
                            <tr>
                                <td>{{ $line->id }}</td>
                                <td>{{ $line->group }}</td>
                                <td>{{ $line->key }}</td>
                                <td>{{ Str::limit($line->text['ru'], 20) }}</td>
                                <td>{{ Str::limit($line->text['en'], 20) }}</td>
                                <td>{{ Str::limit($line->text['pl'], 20) }}</td>
                                <td><input type="text" class="form-control" disabled value="__('{{ $line->group }}.{{ $line->key }}')"> </td>
                                <td>
                                    <button wire:click.prevent="deleteLineConfirmation({{ $line }})" class="btn btn-danger btn-sm" >
                                        <i class="fas fa-trash"></i>
                                    </button>
                                    <button wire:click.prevent="editLine({{ $line }})" class="btn btn-success btn-sm" >
                                        <i class="fas fa-edit"></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {{--        @endif--}}
    </div>
    <div class="mt-5 mb-5">
        {{ $lines->links() }}
    </div>

    <div class="modal" @if ($showModal) style="display:block" @endif>
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form >
                    <div class="modal-header">
                        <h5 class="modal-title">TEST</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close" wire:click="closeModal">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Текст RU:
                        <br/>
                        <input wire:model="editLine.text.ru" class="form-control"/>
                        @error('editLine.text.ru')
                            <div style="font-size: 11px; color: red">{{ $message }}</div>
                        @enderror
                        <br/>
                        Текст EN:
                        <br/>
                        <input wire:model="editLine.text.en" class="form-control"/>
                        @error('editLine.text.en')
                            <div style="font-size: 11px; color: red">{{ $message }}</div>
                        @enderror
                        <br/>
                        Текст EN:
                        <br/>
                        <input wire:model="editLine.text.pl" class="form-control"/>
                        @error('editLine.text.pl')
                        <div style="font-size: 11px; color: red">{{ $message }}</div>
                        @enderror
                        <br/>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" wire:click="saveEditLine">Зберегти</button>
                        <button type="button" class="btn btn-secondary" wire:click="closeModal" data-dismiss="modal">Закрити
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>